base_url = "https://aws-studyguide.vercel.app/"
title = "Bit's Certification Guides"
description = "Short articles breaking down key strategies and concepts for AWS certifications."
default_language = "en"
theme = "DeepThought"
output_dir = "public"
compile_sass = true
minify_html = false
ignored_content = []
hard_link_static = false

taxonomies = [
    { name = "exams", feed = true, paginate_by = 10 },
    { name = "topics", feed = true, paginate_by = 10 },
]

build_search_index = true

[markdown]
highlight_code = true
extra_syntaxes = []
highlight_theme = "one-dark"
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[link_checker]
skip_prefixes = ["http://[2001:db8::]/"]
skip_anchor_prefixes = ["https://caniuse.com/"]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[search]
include_title = true
include_description = false
include_path = false
include_content = true
[translations]

[extra]
katex.enabled = true
katex.auto_render = true

chart.enabled = true
mermaid.enabled = true
galleria.enabled = true

navbar_items = [
    { code = "en", nav_items = [
        { url = "$BASE_URL/", name = "Home" },
        { url = "$BASE_URL/articles", name = "Articles" },
        { url = "$BASE_URL/topics", name = "Topics" },
    ] },
]

[extra.favicon]
favicon_16x16 = "/icons/favicon.png"
favicon_32x32 = "/icons/favicon.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

[extra.author]
name = "Bit the Chipmunk, AWS Expert"
avatar = "images/bit-the-chipmunk.png"

[extra.social]
# facebook = "RatanShreshtha"
# github = "RatanShreshtha"
# linkedin = "ratanshreshtha"
# stackoverflow = "3728911"
# email = "deepthought@gmail.com"

[extra.analytics]
google = "G-JPHGX4YXVE"

[extra.commenting]
disqus = "deepthought-theme"

[extra.mapbox]
enabled = true
access_token = "pk.eyJ1IjoicmF0YW5zaHJlc2h0aGEiLCJhIjoiY2tla2s2NmM3MDd0ZzJzbXFtc3Y2YmU0NyJ9.0RhUnJPKbxHWw3xGPnnBlA"
